### ISSUE TITLE
Document backup / recover plans

### ISSUE THREAD

**Issue by dlebauer** [terraref/documentation#11]
I made a new page to document how data are being archived and backed up. 

Can be edited on [github](https://github.com/terraref/documentation/edit/master/data_backup.md) or [gitbook](https://www.gitbook.com/book/terraref/terraref-documentation/edit#/edit/master/data_backup.md).
- [x] please update the use of NCSA crashplan (@robkooper)
- [ ] nightly dumps to nearline storage (@jdmaloney)

**Comment by jdmaloney** [comment]
@dlebauer Going to both of these links give me errors.  403 Error Forbidden on the gitbook link, 404 Page Not Found on the github link.

**Comment by dlebauer** [comment]
@jdmaloney try again. The files were renamed data_backups.md --> data_backup.md (and I've corrected the links above)

**Comment by jdmaloney** [comment]
@dlebauer Still no luck, getting the same errors as before (though the links do appear to have been corrected, I get taken to the page named without an "s")

**Comment by dlebauer** [comment]
How about
https://github.com/terraref/documentation/edit/master/data-backup.md

**Comment by jdmaloney** [comment]
I have updated this and submitted a pull request.  Closing issue
